# Generated by Django 6.0.3 on 2026-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miner_api", "0007_savedtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedtext",
            name="hsk_level",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
